src/dennea/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('', include('error_pages.urls')),
    path('', include('accounts.urls')),
    path('', include('catalog.urls')),
    path('', include('shopping_cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

src/shopping_cart/urls.py
from django.urls import path, include

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    purchase_success,
    get_vendor_pending_orders,
    get_pending_orders,
    get_customer_pending_orders,
    get_driver_deliveries,
    get_order_details,
    get_customer_order_details,
    get_vendor_order_details,
    get_driver_order_details,
)

urlpatterns = [
    path('cart/', include(([
        path('add-to-cart/<slug:slug>/', add_to_cart, name="add_to_cart"),
        path('order-summary/', order_details, name="order_summary"),
        path('success/', purchase_success, name='purchase_success'),
        path('item/delete/<int:item_id>/', delete_from_cart, name='delete_item'),
    ], 'shopping_cart'), namespace='shopping_cart')),
    path('orders/', include(([
        path('', get_pending_orders, name="orders"),
        path('vendor/<slug:slug>/', get_vendor_pending_orders, name='vendor-orders'),
        path('customer/<slug:slug>/', get_customer_pending_orders, name='customer-orders'),
        path('driver/<slug:slug>/', get_driver_deliveries, name='driver-orders'),
        path('<uuid:slug>/details', get_order_details, name='order-details'),
        path('<uuid:slug>/customer-details', get_customer_order_details, name='customer-details'),
        path('<uuid:slug>/vendor-details', get_vendor_order_details, name='vendor-details'),
        path('<uuid:slug>/delivery-details', get_driver_order_details, name='driver-details'),
    ], 'orders'), namespace='orders')),
]

src/catalog/models/category.py
from django.db import models
from django.shortcuts import reverse
from django.utils.text import slugify

class Category(models.Model):
    slug = models.SlugField(max_length=128, unique=True, blank=True)
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    # a2.parent = a1; a1.children.all()
    parent = models.ForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    visible = models.BooleanField(default=True)
    show_on_homepage = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

src/catalog/forms/products.py
from django import forms

from catalog.models import Product, ProductAttribute, PredefineAttributeValue


class ProductForm(forms.ModelForm):
    name = forms.CharField(max_length=128, min_length=2, strip=True, widget=forms.TextInput(
        attrs={'class ': ''}))
    description = forms.CharField(
        strip=True, widget=forms.Textarea(attrs={'class ': ''}))
    stock_quantity = forms.IntegerField(widget=forms.NumberInput(
        attrs={'class': ''}))
    price = forms.DecimalField(max_digits=6, decimal_places=2, widget=forms.NumberInput(
        attrs={'class': ''}))

    class Meta:
        model = Product
        fields = [
            'name',
            'description',
            'stock_quantity',
            'price',
        ]


class ProductDetailsForm(forms.ModelForm):
    name = forms.CharField(max_length=128, min_length=2, strip=True, widget=forms.TextInput(
        attrs={'class ': ''}))
    description = forms.CharField(
        strip=True, widget=forms.Textarea(attrs={'class ': ''}))
    published = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(attrs={'class': ''}))
    mark_as_new = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(attrs={'class': ''}))
    not_returnable = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(attrs={'class': ''}))
    show_on_homepage = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(attrs={'class': ''}))
    featured = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(attrs={'class': ''}))
    allow_reviews = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(attrs={'class': ''}))
    vendor_comments = forms.CharField(
        strip=True, widget=forms.Textarea(attrs={'class ': ''}))

    class Meta:
        model = Product
        fields = [
            'name',
            'description',
            'published',
            'mark_as_new',
            'not_returnable',
            'show_on_homepage',
            'featured',
            'allow_reviews',
            'vendor_comments'
        ]


class ProductStockForm(forms.ModelForm):
    stock_quantity = forms.IntegerField(
        min_value=0, widget=forms.NumberInput(attrs={'class': ''}))
    sold = forms.IntegerField(
        min_value=0, widget=forms.NumberInput(attrs={'class': ''}))

    class Meta:
        model = Product
        fields = [
            'stock_quantity',
            'sold',
        ]


class PriceForm(forms.ModelForm):
    price = forms.DecimalField(max_digits=6, decimal_places=2, widget=forms.NumberInput(
        attrs={'class': ''}))
    sales_rate = forms.FloatField(min_value=0.0, widget=forms.NumberInput(
        attrs={'class': '', 'step': "0.01"}))
    on_sale = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(attrs={'class': ''}))
    is_free = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(attrs={'class': ''}))
    call_for_price = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(attrs={'class': ''}))

    class Meta:
        model = Product
        fields = [
            'price',
            'sales_rate',
            'on_sale',
            'call_for_price',
        ]


class DimensionForm(forms.ModelForm):
    weight = forms.DecimalField(max_digits=4, decimal_places=2, widget=forms.NumberInput(
        attrs={'class': ''}))
    length = forms.DecimalField(max_digits=4, decimal_places=2, widget=forms.NumberInput(
        attrs={'class': ''}))
    width = forms.DecimalField(max_digits=4, decimal_places=2, widget=forms.NumberInput(
        attrs={'class': ''}))
    height = forms.DecimalField(max_digits=4, decimal_places=2, widget=forms.NumberInput(
        attrs={'class': ''}))

    class Meta:
        model = Product
        fields = [
            'weight',
            'length',
            'width',
            'height',
        ]


class ProductAttributeForm(forms.ModelForm):

    attributes = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        queryset=PredefineAttributeValue.objects.all().order_by("attribute")
    )

    class Meta:
        model = Product
        fields = [
            'attributes',
        ]

src/catalog/views/products.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, Http404
from django.shortcuts import render, redirect

from accounts.models import Vendor
from photos.models import Album
from users.decorators import vendor_required
from catalog.forms import (ProductForm,
                           PriceForm,
                           DimensionForm,
                           ProductAttributeForm,
                           ProductDetailsForm,
                           ProductStockForm)
from catalog.models import Product, PredefineAttributeValue, ProductAttribute

@login_required
@vendor_required
def vendor_products(request, slug):
    template_name = 'products/vendor_products.html'
    context = {}

    if slug is None or slug == "":
        return redirect('not-found')

    vendor = Vendor.objects.get(slug=slug)

    if vendor is None:
        return redirect('not-found')

    if not vendor.user == request.user:
        return redirect('forbidden')

    context["vendor"] = vendor

    return render(request, template_name, context)

@login_required
@vendor_required
def create_product(request):
    template_name = 'products/create_product.html'
    context = {}
    if request.method == 'POST':
        form = ProductForm(request.POST or None)
        if form.is_valid():
            product = form.save(commit=False)
            product.vendor = request.user.vendor
            product.acl = request.user.acl
            product.album = Album.objects.create(name=product.name, owner=request.user)
            product.save()
            return redirect(product.get_absolute_url())
    else:
        form = ProductForm()
    context["form"] = form
    return render(request, template_name, context)

@login_required
@vendor_required
def product_details(request, slug):
    template_name = 'products/product_details.html'
    context = {}

    if slug is None or slug == "":
        return redirect('not-found')

    product = Product.objects.get(slug=slug)

    if product is None:
        return redirect('not-found')

    if not product.vendor == request.user.vendor:
        return redirect('forbidden')

    if request.method == 'POST':
        form = ProductDetailsForm(request.POST or None, instance=product)
        if form.is_valid():
            form.save()
            return redirect(product.get_absolute_url())
    else:
        form = ProductDetailsForm(instance=product)
    context["form"] = form
    context["product"] = product
    return render(request, template_name, context)

@login_required
@vendor_required
def product_price(request, slug):
    template_name = 'products/product_price.html'
    context = {}

    if slug is None or slug == "":
        return redirect('not-found')

    product = Product.objects.get(slug=slug)

    if product is None:
        return redirect('not-found')

    if not product.vendor == request.user.vendor:
        return redirect('forbidden')

    if request.method == 'POST':
        form = PriceForm(request.POST or None, instance=product)
        if form.is_valid():
            form.save()
            return redirect(product.get_price_url())
    else:
        form = PriceForm(instance=product)
    context["form"] = form
    context["product"] = product
    return render(request, template_name, context)

@login_required
@vendor_required
def product_attributes(request, slug):
    template_name = 'products/product_attribute.html'
    context = {}

    if slug is None or slug == "":
        return redirect('not-found')

    product = Product.objects.get(slug=slug)

    if product is None:
        return redirect('not-found')

    if not product.vendor == request.user.vendor:
        return redirect('forbidden')
    
    attributes = ProductAttribute.objects.all()

    # if request.method == 'POST':
    #     form = ProductAttributeForm(request.POST or None, instance=product)
    #     if form.is_valid():
    #         form.save()
    #         return redirect(product.get_attribute_url())
    # else:
    #     form = ProductAttributeForm(instance=product)
    # context["form"] = form

    context["attributes"] = attributes
    context["product"] = product
    return render(request, template_name, context)

@login_required
@vendor_required
def set_attribute_values(request, slug):
    if slug is None or slug == "":
        return Http404

    product = Product.objects.get(slug=slug)

    if product is None:
        return Http404

    if request.method == "POST" and request.is_ajax():
        values = PredefineAttributeValue.objects.filter(id__in=request.POST.getlist('attribute_values'))
        product.attributes.clear()
        product.attributes.add(*values)
        data = {'success': True, 'message': 'Attributes added to product.'}
        return JsonResponse(data, status=200)

@login_required
def product_list(request):
    template_name = 'products/product_list.html'
    context = {}

    products = Product.objects.all()
    context['products'] = products

    return render(request, template_name, context)

src/catalog/templates/products/_attribute_form.html
<form id="attr-form" class="ui large container form" method="POST" novalidate action="{{ product.set_attribute_url }}">
    {% csrf_token %}
    {% for attr in attributes %}
        <h5>{{ attr.name }}</h5>
        <div class="ten fields">
        {% for val in attr.values.all %}
            <div class="field">
                <div class="ui checkbox">
                    {% if val in product.attributes.all %}
                        <input name="attribute_values" value="{{ val.pk }}" type="checkbox" tabindex="0" class="hidden" checked>
                    {% else %}
                        <input name="attribute_values" value="{{ val.pk }}" type="checkbox" tabindex="0" class="hidden">
                    {% endif %}
                    <label>{{ val.name }}</label>
                </div>
            </div>
        {% endfor %}
       </div>
    {% endfor %}
    <button class="ui teal button" type="submit">Submit</button>
</form>

src/catalog/templates/products/_details_form.html
<form class="ui large container form" method="POST" novalidate>
    {% csrf_token %}
    <div class="field">
        {{ form.name.errors }}
        <label for="{{ form.name.id_for_label }}">Name:</label>
        {{ form.name }}
    </div>
    <div class="field">
        {{ form.description.errors }}
        <label for="{{ form.description.id_for_label }}">Description:</label>
        {{ form.description }}
    </div>
    <div class="field">
        <div class="ui checkbox">
            {{ form.published.errors }}
            {{ form.published }}
            <label for="{{ form.published.id_for_label }}">Published</label>
        </div>
    </div>
    <div class="field">
        <div class="ui checkbox">
            {{ form.mark_as_new.errors }}
            {{ form.mark_as_new }}
            <label for="{{ form.mark_as_new.id_for_label }}">Mark as new</label>
        </div>
    </div>
    <div class="field">
        <div class="ui checkbox">
            {{ form.not_returnable.errors }}
            {{ form.not_returnable }}
            <label for="{{ form.not_returnable.id_for_label }}">Returnable</label>
        </div>
    </div>
    <div class="field">
        <div class="ui checkbox">
            {{ form.show_on_homepage.errors }}
            {{ form.show_on_homepage }}
            <label for="{{ form.show_on_homepage.id_for_label }}">Show on home page</label>
        </div>
    </div>
    <div class="field">
        <div class="ui checkbox">
            {{ form.featured.errors }}
            {{ form.featured }}
            <label for="{{ form.featured.id_for_label }}">Featured</label>
        </div>
    </div>
    <div class="field">
        <div class="ui checkbox">
            {{ form.allow_reviews.errors }}
            {{ form.allow_reviews }}
            <label for="{{ form.allow_reviews.id_for_label }}">Allow reviews</label>
        </div>
    </div>
    <div class="field">
        {{ form.vendor_comments.errors }}
        <label for="{{ form.vendor_comments.id_for_label }}">Vendor Comments:</label>
        {{ form.vendor_comments }}
    </div>
    <button class="ui teal button" type="submit">Submit</button>
</form>

src/catalog/templates/products/_price_form.html
<form class="ui large container form" method="POST" novalidate>
    {% csrf_token %}
    <div class="field">
        {{ form.price.errors }}
        <label for="{{ form.price.id_for_label }}">Price:</label>
        {{ form.price }}
    </div>
    <div class="field">
        <div class="ui checkbox">
            {{ form.on_sale.errors }}
            {{ form.on_sale }}
            <label for="{{ form.on_sale.id_for_label }}">On Sale</label>
        </div>
    </div>
    <div class="field">
        {{ form.sales_rate.errors }}
        <label for="{{ form.sales_rate.id_for_label }}">Sales Rate:</label>
        {{ form.sales_rate }}
    </div>
    
    <div class="field">
        <div class="ui checkbox">
            {{ form.is_free.errors }}
            {{ form.is_free }}
            <label for="{{ form.is_free.id_for_label }}">Mark as new</label>
        </div>
    </div>
    <div class="field">
        <div class="ui checkbox">
            {{ form.call_for_price.errors }}
            {{ form.call_for_price }}
            <label for="{{ form.call_for_price.id_for_label }}">Returnable</label>
        </div>
    </div>
    <button class="ui teal button" type="submit">Submit</button>
</form>

src/catalog/templates/products/_tab_headers.html
<a href="{{ product.get_absolute_url }}" {% if details %}class="active item"{% else %}class="item"{% endif %} data-tab="first">Details</a>
<a href="{{ product.get_price_url }}" {% if price %}class="active item"{% else %}class="item"{% endif %} data-tab="second">Price</a>
<a href="{{ product.get_attribute_url }}" {% if attribute %}class="active item"{% else %}class="item"{% endif %} data-tab="third">Attributes</a>
<a class="item" data-tab="fourth">Dimensions</a>

src/catalog/templates/products/create_product.html
{% extends 'dashboard.html' %}

{% block content %}
<div class="ui container">

    <div class="row">
        <div class="sixteen wide column">
            <h1 class="ui header">Create Product</div>

            <form class="ui large container form" method="POST" novalidate>
                {% csrf_token %}
                <div class="field">
                    {{ form.name.errors }}
                    <label for="{{ form.name.id_for_label }}">Name:</label>
                    {{ form.name }}
                </div>
                <div class="field">
                    {{ form.description.errors }}
                    <label for="{{ form.description.id_for_label }}">Description:</label>
                    {{ form.description }}
                </div>
                <div class="field">
                    {{ form.price.errors }}
                    <label for="{{ form.price.id_for_label }}">Price:</label>
                    {{ form.price }}
                </div>
                <div class="field">
                    {{ form.stock_quantity.errors }}
                    <label for="{{ form.stock_quantity.id_for_label }}">Stock Quantity:</label>
                    {{ form.stock_quantity }}
                </div>
                <button class="ui teal button" type="submit">Submit</button>
            </form>
        </div>
    </div>

</div>
{% endblock content %}

src/catalog/templates/products/product_attribute.html
{% extends 'dashboard.html' %}

{% block content %}
<div class="ui container">

    <div class="row">
        <div class="sixteen wide column">
            <h1 class="ui header">{{ product.name }}</div>

            <div class="ui top attached tabular menu">
                {% include 'products/_tab_headers.html' with attribute=True %}
            </div>
            <div class="ui bottom attached tab segment" data-tab="first">
                First
            </div>
            <div class="ui bottom attached tab segment" data-tab="second">
                Second
            </div>
            <div class="ui bottom attached tab active segment" data-tab="third">
                <div class="ui positive hidden message">
                    <i class="close icon"></i>
                    <p id="results"></p>
                </div>
                {% include 'products/_attribute_form.html' %}
            </div>
            <div class="ui bottom attached tab segment" data-tab="fourth">
                Fourth
            </div>
        </div>
    </div>

</div>
{% endblock content %}

{% block javascript %}
<script>
    $(document).ready(function() {
        $('.ui.checkbox').checkbox();

        $("#attr-form").on("submit", function(e) {
            e.preventDefault();

            $.ajax({
                data: $(this).serialize(),
                type: $(this).attr('method'),
                url: $(this).attr('action'),
                success: function(response) {
                    if(response['success']) {
                        console.log(response);
                        $("#results").html(response["message"]);
                        $(".ui.positive.message").removeClass("hidden");
                        $(".ui.positive.message").addClass("visible");
                    }
                    if(response['error']) {
                    }
                },
                error: function (request, status, error) {
                    console.log(request.responseText);
                }
            });
        });
    });
</script>
{% endblock javascript %}

src/catalog/templates/products/product_details.html
{% extends 'dashboard.html' %}

{% block content %}
<div class="ui container">

    <div class="row">
        <div class="sixteen wide column">
            <h1 class="ui header">{{ product.name }}</div>

            <div class="ui top attached tabular menu">
                {% include 'products/_tab_headers.html' with details=True %}
            </div>
            <div class="ui bottom attached active tab segment" data-tab="first">
                {% include 'products/_details_form.html' %}
            </div>
            <div class="ui bottom attached tab segment" data-tab="second">
                Second
            </div>
            <div class="ui bottom attached tab segment" data-tab="third">
                Third
            </div>
        </div>
    </div>

</div>
{% endblock content %}

{% block javascript %}
<script>
    $(document).ready(function() {
        //$('.menu .item').tab();
    });
</script>
{% endblock javascript %}

src/catalog/templates/products/product_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="ui container">
    <div class="ui padded grid">

        <div class="row">
            <div class="sixteen wide column">
                <h1 class="ui dividing header">Products</h1>
            </div>
        </div>

        <div class="row">
            {% for product in products %}
            <div class="four wide column">
                <div class="ui segments">
                    <div class="ui raised segment">
                        <a class="ui red ribbon label">$ {{ product.price }}</a>
                        <div class="image">
                            <img class="ui fluid image" src="{{ product.get_first_photo }}">
                        </div>
                    </div>

                    <div class="ui segment">
                        <div class="ui header">{{ product.name }}</div>
                        <p>{{ product.description|truncatechars:100 }}</p>
                    </div>
                    <div class="ui horizontal segments">
                        <div class="ui segment">
                            <p class="px-3 center aligned" style="font-size: large;"><i class="eye icon"></i></p>
                        </div>
                        <div class="ui segment">
                            <a href="{% url 'shopping_cart:add_to_cart' product.slug %}" class="px-3 center aligned" style="font-size: large;">
                                <i class="cart plus icon"></i>
                            </a>
                        </div>
                        <div class="ui segment">
                            <p class="px-3 center aligned" style="font-size: large;"><i class="heart icon"></i></p>
                        </div>
                    </div>
                    <!-- <div class="ui segment">
                        <p>Bottom</p>
                    </div> -->
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

src/catalog/templates/products/product_price.html
{% extends 'dashboard.html' %}

{% block content %}
<div class="ui container">

    <div class="row">
        <div class="sixteen wide column">
            <h1 class="ui header">{{ product.name }}</div>
            <div class="ui top attached tabular menu">
                {% include 'products/_tab_headers.html' with price=True %}
            </div>
            <div class="ui bottom attached tab segment" data-tab="first">
                First
            </div>
            <div class="ui bottom attached active tab segment" data-tab="second">
                {% include 'products/_price_form.html' %}
            </div>
            <div class="ui bottom attached tab segment" data-tab="third">
                Third
            </div>
        </div>
    </div>

</div>
{% endblock content %}

{% block javascript %}
<script>
    $(document).ready(function() {
        //$('.menu .item').tab();
    });
</script>
{% endblock javascript %}

src/catalog/templates/products/vendor_products.html
{% extends 'dashboard.html' %}

{% block content %}
<div class="ui container">

    <div class="row">
        <div class="sixteen wide column">
            <h1 class="ui header">Products</div>

            <a class="ui button fluid" href="{% url 'products:create-product' %}">Create</a>

            <table class="ui basic table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Sold</th>
                        <th>Sales</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in vendor.get_products %}
                        <tr>
                            <td>{{ product.name }}</td>
                            <td>{{ product.price }}</td>
                            <td>{{ product.stock_quantity }}</td>
                            <td>{{ product.sold }}</td>
                            <td>{{ product.get_sales }}</td>
                            <td><a href="{{ product.get_absolute_url }}">Details</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>
{% endblock content %}