src/dennea/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('', include('error_pages.urls')),
    path('', include('accounts.urls')),
    path('', include('catalog.urls')),
    path('', include('shopping_cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

src/shopping_cart/urls.py
from django.urls import path, include

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    purchase_success,
    get_vendor_pending_orders,
    get_pending_orders,
    get_customer_pending_orders,
    get_driver_deliveries,
    get_order_details,
    get_customer_order_details,
    get_vendor_order_details,
    get_driver_order_details,
)

urlpatterns = [
    path('cart/', include(([
        path('add-to-cart/<slug:slug>/', add_to_cart, name="add_to_cart"),
        path('order-summary/', order_details, name="order_summary"),
        path('success/', purchase_success, name='purchase_success'),
        path('item/delete/<int:item_id>/', delete_from_cart, name='delete_item'),
    ], 'shopping_cart'), namespace='shopping_cart')),
    path('orders/', include(([
        path('', get_pending_orders, name="orders"),
        path('vendor/<slug:slug>/', get_vendor_pending_orders, name='vendor-orders'),
        path('customer/<slug:slug>/', get_customer_pending_orders, name='customer-orders'),
        path('driver/<slug:slug>/', get_driver_deliveries, name='driver-orders'),
        path('<uuid:slug>/details', get_order_details, name='order-details'),
        path('<uuid:slug>/customer-details', get_customer_order_details, name='customer-details'),
        path('<uuid:slug>/vendor-details', get_vendor_order_details, name='vendor-details'),
        path('<uuid:slug>/delivery-details', get_driver_order_details, name='driver-details'),
    ], 'orders'), namespace='orders')),
]

src/templates/partials/base/_footer.html
{% load static %}
<div class="ui vertical footer segment" style="margin-top: 3rem; border-top: 3px solid rgb(79,163,190); border-bottom: 3px solid rgb(79,163,190);">
    <div class="ui center aligned container pt-3">
        <div class="ui stackable divided grid">
            <div class="three wide column">
                <h4 class="ui header">Group 1</h4>
                <div class="ui link list">
                    <a class="item" href="#">Link One</a>
                    <a class="item" href="#">Link Two</a>
                    <a class="item" href="#">Link Three</a>
                    <a class="item" href="#">Link Four</a>
                    </div>
                </div>
                <div class="three wide column">
                    <h4 class="ui header">Group 2</h4>
                    <div class="ui link list">
                    <a class="item" href="#">Link One</a>
                    <a class="item" href="#">Link Two</a>
                    <a class="item" href="#">Link Three</a>
                    <a class="item" href="#">Link Four</a>
                    </div>
                </div>
                <div class="three wide column">
                    <h4 class="ui header">Group 3</h4>
                    <div class="ui link list">
                        <a class="item" href="#">Link One</a>
                        <a class="item" href="#">Link Two</a>
                        <a class="item" href="#">Link Three</a>
                        <a class="item" href="#">Link Four</a>
                    </div>
                </div>
                <div class="seven wide column">
                    <h4 class="ui header">Footer Header</h4>
                    <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
                </div>
            </div>
            <div class="ui inverted section divider"></div>
            <img class="ui centered mini image" src="{% static 'images/aug-logo.png' %}">
            <div class="ui horizontal inverted small divided link list">
                <a class="item" href="#">Site Map</a>
                <a class="item" href="#">Contact Us</a>
                <a class="item" href="#">Terms and Conditions</a>
                <a class="item" href="#">Privacy Policy</a>
            </div>
        </div>
    </div>
</div>

src/templates/partials/base/_navbar.html
{% load static %}
{% load cart_template_tag %}

<div class="ui fixed menu borderless" style="border-bottom: 3px solid rgb(79,163,190);">
    <div class="ui container">
        <a class="header item" href="{% url 'home' %}">
            <img class="logo" src="{% static 'images/aug-logo.png' %}" />
            Dennea
        </a>
        <a class="item" href="{% url 'home' %}">Home</a>
        {% if request.user.is_authenticated %}
            {% if request.user.is_customer %}
                <a class="item" href="{% url 'shopping_cart:order_summary' %}">
                    <i class="icon cart"></i>
                    <div class="floating ui teal circular label" style="margin-top:1.2rem !important; margin-right:60em !important;">
                        {{ request.user.customer.get_basket_count }}
                    </div>
                </a>
                <a class="item" href="{% url 'orders:customer-orders' request.user.customer.slug %}">
                    Orders
                </a>
            {% endif %}
            <a class="item" href="{% url 'products:product-list' %}">Products</a>
            <div class="ui simple dropdown item right aligned">
                {{ request.user.name }} <i class="dropdown icon"></i>
                <div class="menu">
                    <a class="item" href="#">Profile</a>
                    <a class="item" href="#">Link Item</a>
                    <div class="divider"></div>
                    <div class="header">Header Item</div>
                    <a class="item" href="#">Settings</a>
                    <a class="item" href="{% url 'logout' %}">Logout</a>
                </div>
            </div>
        </div>
        {% else %}
            <a class="item" href="{% url 'login' %}">Login</a>
            <a class="item" href="{% url 'user_signup' %}">Signup</a>
        {% endif %}
    </div>
</div>

src/templates/partials/base/_sidenav.html
<div class="ui fluid vertical pointing menu">
    <a href="#" class="active item">
        Applications
    </a>
    <a href="#" class="item">
        Work History
    </a>
    <a href="#" class="item">
        Education History
    </a>
    <a href="#" class="item">
        References
    </a>
    <a class="item">
        Documents
    </a>
    <a class="item">
        Messages
    </a>
    <a class="item">
        Friends
    </a>
</div>