src/dennea/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('', include('error_pages.urls')),
    path('', include('accounts.urls')),
    path('', include('catalog.urls')),
    path('', include('shopping_cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

src/shopping_cart/urls.py
from django.urls import path, include

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    purchase_success,
    get_vendor_pending_orders,
    get_pending_orders,
    get_customer_pending_orders,
    get_driver_deliveries,
    get_order_details,
    get_customer_order_details,
    get_vendor_order_details,
    get_driver_order_details,
)

urlpatterns = [
    path('cart/', include(([
        path('add-to-cart/<slug:slug>/', add_to_cart, name="add_to_cart"),
        path('order-summary/', order_details, name="order_summary"),
        path('success/', purchase_success, name='purchase_success'),
        path('item/delete/<int:item_id>/', delete_from_cart, name='delete_item'),
    ], 'shopping_cart'), namespace='shopping_cart')),
    path('orders/', include(([
        path('', get_pending_orders, name="orders"),
        path('vendor/<slug:slug>/', get_vendor_pending_orders, name='vendor-orders'),
        path('customer/<slug:slug>/', get_customer_pending_orders, name='customer-orders'),
        path('driver/<slug:slug>/', get_driver_deliveries, name='driver-orders'),
        path('<uuid:slug>/details', get_order_details, name='order-details'),
        path('<uuid:slug>/customer-details', get_customer_order_details, name='customer-details'),
        path('<uuid:slug>/vendor-details', get_vendor_order_details, name='vendor-details'),
        path('<uuid:slug>/delivery-details', get_driver_order_details, name='driver-details'),
    ], 'orders'), namespace='orders')),
]

src/shopping_cart/models.py
import uuid
from django.db import models

from catalog.models import Product
from accounts.models import Vendor, Customer, Driver

# Create your models here.
class Basket(models.Model):
    slug = models.SlugField(unique=True, default=uuid.uuid1, blank=True)
    customer = models.OneToOneField(Customer, on_delete=models.CASCADE, blank=True)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.product.price for item in self.items.all()])

    def add_to_basket(self, product):
        order_item = OrderItem.objects.create(product=product, basket=self, vendor=product.vendor)
        self.items.add(order_item)

    def empty_basket(self):
        self.items.clear()

    def __str__(self):
        return f"{self.customer.get_name}'s basket"


class Order(models.Model):
    slug = models.SlugField(unique=True, default=uuid.uuid1, blank=True)
    ref_code = models.CharField(max_length=15)
    customer = models.ForeignKey(Customer, related_name='orders', on_delete=models.SET_NULL, null=True)
    is_fulfilled = models.BooleanField(default=False)
    date_ordered = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{0} - {1}'.format(self.customer, self.ref_code)

    @property
    def get_order_total(self):
        return sum([item.product.price for item in self.items.all()])


class OrderItem(models.Model):
    slug = models.SlugField(unique=True, default=uuid.uuid1, blank=True)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.SET_NULL, null=True, blank=True)
    basket = models.ForeignKey(Basket, on_delete=models.SET_NULL, related_name='items', null=True, blank=True)
    vendor = models.ForeignKey(Vendor, related_name='order_items', on_delete=models.SET_NULL, null=True, blank=True)
    driver = models.ForeignKey(Driver, related_name='deliveries', on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE, null=True, blank=True)
    is_fulfilled = models.BooleanField(default=False)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)

    @property
    def get_customer(self):
        return self.order.customer.get_company_name

    def __str__(self):
        return self.product.name

src/shopping_cart/views.py
import datetime
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404

from accounts.models import Vendor, Customer, Driver
from catalog.models import Product
from users.models import User

from .extras import generate_order_id
from .models import Order, OrderItem, Basket

def get_user_pending_order(request):
    # get order for the correct user
    customer = get_object_or_404(Customer, user=request.user)
    order = Order.objects.filter(customer=customer, is_fulfilled=False)
    if order.exists():
        # get the only order in the list of filtered orders
        return order[0]
    return 0

def get_vendor_pending_orders(request, slug):
    template_name = 'orders/vendor_pending_orders.html'
    vendor = get_object_or_404(Vendor, user=request.user, slug=slug)
    orders = OrderItem.objects.filter(vendor=vendor, is_ordered=True, is_fulfilled=False)
    data = {}
    data['orders'] = orders
    return render(request, template_name, data)

@login_required()
def get_driver_deliveries(request, slug):
    template_name = 'orders/driver_deliveries.html'
    driver = get_object_or_404(Driver, user=request.user, slug=slug)
    orders = OrderItem.objects.filter(driver=driver, is_fulfilled=False)
    data = {}
    data['orders'] = orders
    return render(request, template_name, data)

@login_required()
def get_pending_orders(request):
    template_name = 'orders/pending_orders.html'
    orders = OrderItem.objects.filter(is_fulfilled=False)
    data = {}
    data['orders'] = orders
    return render(request, template_name, data)

@login_required()
def get_customer_pending_orders(request, slug):
    template_name = 'orders/customer_pending_orders.html'
    customer = Customer.objects.get(slug=slug)
    orders = Order.objects.filter(customer=customer, is_fulfilled=False)
    data = {}
    data['orders'] = orders
    return render(request, template_name, data)

@login_required()
def get_order_details(request, slug):
    template_name = 'orders/order_details.html'
    context = {}
    order = Order.objects.get(slug=slug)
    context["order"] = order
    return render(request, template_name, context)

@login_required()
def get_customer_order_details(request, slug):
    template_name = 'orders/customer_order_details.html'
    order = Order.objects.get(slug=slug)
    data = {}
    data['order'] = order
    return render(request, template_name, data)

@login_required()
def get_vendor_order_details(request, slug):
    template_name = 'orders/vendor_order_details.html'
    order = OrderItem.objects.get(slug=slug, vendor=request.user.vendor)
    data = {}
    data['order'] = order
    return render(request, template_name, data)

@login_required()
def get_driver_order_details(request, slug):
    template_name = 'orders/driver_order_details.html'
    order = OrderItem.objects.get(slug=slug, driver=request.user.driver)
    data = {}
    data['order'] = order
    return render(request, template_name, data)

@login_required
def add_to_cart(request, slug):
    product = Product.objects.get(slug=slug)
    customer = get_object_or_404(Customer, user=request.user)

    customer.basket.add_to_basket(product)

    messages.info(request, "item added to cart")
    return redirect('products:product-list')

# @login_required()
# def add_to_cart(request, **kwargs):
#     # get the user profile
#     customer = get_object_or_404(Customer, user=request.user)
#     # filter products by id
#     product = Product.objects.filter(id=kwargs.get('item_id', "")).first()
#     # check if the user already owns this product
#     # if product in request.user.profile.ebooks.all():
#     #     messages.info(request, 'You already own this ebook')
#     #     return redirect(reverse('products:product-list')) 
#     # create orderItem of the selected product
    
#     # create order associated with the user
#     user_order, status = Order.objects.get_or_create(customer=customer, is_fulfilled=False)
#     order_item, status = OrderItem.objects.get_or_create(order=user_order, product=product, vendor=product.vendor)
#     # user_order.items.add(order_item)
#     if status:
#         # generate a reference code
#         user_order.ref_code = generate_order_id()
#         user_order.save()

    # show confirmation message and redirect back to the same page
    # messages.info(request, "item added to cart")
    # return redirect('products:product-list')

@login_required()
def delete_from_cart(request, item_id):
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request, "Item has been deleted")
    return redirect('shopping_cart:order_summary')


@login_required()
def order_details(request, template_name='shopping_cart/order_summary.html', **kwargs):
    customer = get_object_or_404(Customer, user=request.user)
    context = {
        'order': customer.basket
    }
    return render(request, template_name, context)

def purchase_success(request):
    # a view signifying the transcation was successful
    customer = Customer.objects.get(user=request.user)
    order = Order.objects.create(customer=customer, ref_code=generate_order_id())

    for item in customer.basket.get_cart_items():
        item.order = order
        item.is_ordered = True
        item.save()

        product = item.product
        product.sold = product.sold + 1
        product.stock_quantity = product.stock_quantity - 1
        product.save()

    customer.basket.empty_basket()
    
    return render(request, 'shopping_cart/purchase_success.html', {})

src/shopping_cart/templates/orders/customer_order_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="ui container">
    <div class="ui padded grid">

        <div class="row">
            <div class="sixteen wide column">
                <h1 class="ui header">Order</div>

                <table class="ui basic table">
                    <thead>
                        <tr>
                            <th>Product</th>
                            <th>Price</th>
                            <th>Date</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in order.items.all %}
                            <tr>
                                <td>{{ item.product.name }}</td>
                                <td>{{ item.product.price }}</td>
                                <td>{{ item.date_added }}</td>
                                <td><a href="#">Details</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/shopping_cart/templates/orders/customer_pending_orders.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="ui container">
    <div class="ui padded grid">

        <div class="row">
            <div class="sixteen wide column">
                <h1 class="ui dividing header">Orders</h1>
            </div>
        </div>

        <div class="row">
            <div class="sixteen wide column">
                <table class="ui basic table">
                    <thead>
                        <tr>
                            <th>Customer</th>
                            <th>Date</th>
                            <th>Order Details</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in orders %}
                            <tr>
                                <td>{{ order.customer.get_name }}</td>
                                <td>{{ order.date_ordered }}</td>
                                <td><a href="{% url 'orders:customer-details' order.slug %}">View</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

src/shopping_cart/templates/orders/vendor_order_details.html
{% extends 'dashboard.html' %}

{% block content %}
<div class="ui container">

    <div class="row">
        <div class="sixteen wide column">
            <h1 class="ui header">Order</div>

            <p>{{ order.product.name }}</p>
            <p>{{ order.get_customer }}</p>
            <p>{{ order.product.price }}</p>
            <p>{{ order.date_added }}</p>
        </div>
    </div>

</div>
{% endblock content %}

src/shopping_cart/templates/orders/vendor_pending_orders.html
{% extends 'dashboard.html' %}

{% block content %}
<div class="ui container">

    <div class="row">
        <div class="sixteen wide column">
            <h1 class="ui header">Orders</div>

            <table class="ui basic table">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Customer</th>
                        <th>Price</th>
                        <th>Date</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                        <tr>
                            <td>{{ order.product.name }}</td>
                            <td>{{ order.get_customer }}</td>
                            <td>{{ order.product.price }}</td>
                            <td>{{ order.date_added }}</td>
                            <td><a href="{% url 'orders:vendor-details' order.slug %}">Details</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>
{% endblock content %}